"""empty message

Revision ID: 8bd08156f45c
Revises: 
Create Date: 2021-06-01 20:29:38.973640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd08156f45c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'builds', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'builds', type_='foreignkey')
    op.drop_column('builds', 'owner_id')
    # ### end Alembic commands ###
